variables:
  latest-version = 0.88.0
dist:
  name: otel-collector-image
  description: custom OTel collector image
  output_path: ./otel-collector-image
  otelcol_version: {{ variables.latest-version }}
receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v{{ variables.latest-version }}
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/receiver/httpcheckreceiver v{{ variables.latest-version }}

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v{{ variables.latest-version }}
  - gomod:
     go.opentelemetry.io/collector/processor/memorylimiterprocessor v{{ variables.latest-version }}

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v{{ variables.latest-version }}
  - gomod:
      go.opentelemetry.io/collector/exporter/otlphttpexporter v{{ variables.latest-version }}
  - gomod:
      github.com/open-telemetry/opentelemetry-collector-contrib/exporter/signalfxexporter v{{ variables.latest-version }}
