on:
  schedule:
  - cron:  "*/5 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/rubenmgx/Upstream.git"
        source_branch: "main"
        destination_branch: "main"
        sync_tags: "true"
        github_token: ${{ secrets.PAT }}
        
