
on:
  schedule:
  - cron:  "*/5 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "https://github.com/rubenmgx/Upstream.git"
        source_branch: "release/*"
        destination_branch: "release/*"
        sync_tags: "true"
        github_token: ${{ secrets.PAT }}

    - name: Buildah Build
      id: build-image
      uses: redhat-actions/buildah-build@v2
      with:
        image: rubenmgx
        tags: latest ${{ github.sha }}
        containerfiles: |
          ./Dockerfile

    - name: Push To quay.io
      id: push-to-quay
      uses: redhat-actions/push-to-registry@v2
      with:
        image: ${{ steps.build-image.outputs.image }}
        tags: ${{ steps.build-image.outputs.tags }}
        registry: quay.io/rugomez
        username: ${{ secrets.QUAY_BOT_USER }}
        password: ${{ secrets.QUAY_BOT_PASSWORD }}
